version: '3'
services:
  elasticsearch:
    image: ${ELASTIC_IMAGE}
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata1:/usr/share/elasticsearch/data
    ports:
      - ${ELASTIC_PORT}:9200
    networks:
      - esnet

  kibana:
    depends_on:
      - elasticsearch
    image: ${KIBANA_IMAGE}
    container_name: kibana
    environment:
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
    ports:
      - ${KIBANA_PORT}:5601
    networks:
      - esnet

  logstash:
    image: docker.elastic.co/logstash/logstash-oss:6.2.3
    container_name: logstash
    volumes:
      - ./logstash/pipeline/:/usr/share/logstash/pipeline/
    ports:
      - "5044:5044"
      - "5001:5001"
    depends_on:
      - elasticsearch
    networks:
      - esnet

  filebeat:
    image: docker.elastic.co/beats/filebeat:6.2.3
    container_name: filebeat
    volumes:
      - ./filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
      - ./logs:/usr/share/filebeat/logs
    depends_on:
      - logstash
    networks:
      - esnet

volumes:
  esdata1:


networks:
  esnet:
